name: AutoPkg Munki Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v4

        - name: Installera AutoPkg via GitHub Action
        uses: autopkg/setup-autopkg-actions@v0.1.2
        with:
          use-python-version: "3.10"

      - name: Lägg till AutoPkg recipes-repo
        run: autopkg repo-add https://github.com/autopkg/recipes.git

      - name: Kör AutoPkg-recept och importera till Munki
        run: |
          mkdir -p pkgs pkgsinfo icons manifests
          autopkg run -v googlechrome.munki AdobeReader.munki
        env:
          MUNKI_REPO: ${{ github.workspace }}

      - name: Git commit och push
        run: |
          git config user.name "MunkiBot"
          git config user.email "bot@munki.local"
          git checkout -b autopkg-update-${{ github.run_id }}
          git add .
          git commit -m "AutoPkg: uppdaterade paket och pkgsinfo"
          git push origin HEAD

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AutoPkg uppdateringar"
          body: "Automatiska uppdateringar från AutoPkg CLI via GitHub Actions."
          base: main
          branch: autopkg-update-${{ github.run_id }}
