name: AutoPkg Munki Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Kör dagligen kl 06:00 UTC

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Klona ditt repo
        uses: actions/checkout@v4

      - name: Installera AutoPkg (via pipx)
        run: |
          brew install pipx
          pipx ensurepath
          pipx install git+https://github.com/autopkg/autopkg.git

      - name: Lägg till AutoPkg-repo
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git

      - name: Kör AutoPkg-recept och importera till Munki
        run: |
          mkdir -p pkgs pkgsinfo icons manifests
          defaults write com.googlecode.munki.munkiimport repo_path "$GITHUB_WORKSPACE"
          autopkg run -v googlechrome.munki AdobeReader.munki

      - name: Skapa Git branch och commit
        run: |
          git config user.name "MunkiBot"
          git config user.email "bot@munki.local"
          git checkout -b autopkg-update-$(date +'%Y%m%d')
          git add .
          git commit -m "AutoPkg: uppdaterade paket och pkgsinfo"
          git push origin HEAD

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AutoPkg uppdateringar"
          body: "Automatiska uppdateringar från AutoPkg CLI via GitHub Actions."
          base: main
          branch: autopkg-update-${{ github.run_id }}
