name: AutoPkg Munki Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'  # Kör varje vardag kl 06:00

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v4

      - name: Installera Munki
        run: |
          curl -L -o munkitools.pkg https://github.com/munki/munki/releases/download/v6.6.5/munkitools-6.6.5.4711.pkg
          sudo installer -pkg munkitools.pkg -target /

      - name: Installera AutoPkg
        run: |
          brew install --cask autopkgr
          autopkg version

      - name: Lägg till AutoPkg-repo
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git

      - name: Kör AutoPkg-recept och importera till Munki
        run: |
          defaults write com.googlecode.munki.munkiimport repo_path "$GITHUB_WORKSPACE"
          autopkg run -v googlechrome.munki AdobeReader.munki

      - name: Commit ändringar
        run: |
          git config user.name "MunkiBot"
          git config user.email "bot@munki.local"
          git checkout -b autopkg-update-$(date +'%Y%m%d') || git checkout autopkg-update-$(date +'%Y%m%d')
          git add .
          git commit -m "AutoPkg: uppdaterade pkginfo och pkgs" || echo "Inga ändringar att committa"
          git push origin HEAD

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AutoPkg uppdateringar"
          body: "Automatiska uppdateringar från AutoPkg"
          base: main
          branch: autopkg-update-$(date +'%Y%m%d')
