name: AutoPkg Munki Automation

on:
  workflow_dispatch:  # Manuell körning
  schedule:
    - cron: '0 6 * * *'  # Varje dag kl 06:00 UTC

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v4

      - name: Installera AutoPkg via Homebrew
        run: brew install --cask autopkg

      - name: Lägg till AutoPkg recipes repo
        run: autopkg repo-add https://github.com/autopkg/recipes.git

      - name: Kör AutoPkg-recept och importera till Munki
        run: |
          mkdir -p pkgs pkgsinfo icons manifests
          defaults write com.googlecode.munki.munkiimport repo_path "$GITHUB_WORKSPACE"
          autopkg run -v googlechrome.munki AdobeReader.munki

      - name: Commit ändringar
        run: |
          git config user.name "MunkiBot"
          git config user.email "bot@munki.local"
          git checkout -b autopkg-update-$(date +'%Y%m%d')
          git add .
          git commit -m "AutoPkg: uppdaterade paket och pkgsinfo"
          git push origin HEAD

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AutoPkg uppdateringar"
          body: "Automatiska uppdateringar från AutoPkg CLI via GitHub Actions."
          base: main
          branch: autopkg-update-${{ github.run_id }}
