name: AutoPkg Munki Automation

on:
  workflow_dispatch:

jobs:
  autopkg:
    runs-on: macos-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v4

      - name: Installera AutoPkg
        run: |
          brew install --cask autopkgr || echo "Redan installerat"
          autopkg version

      - name: Lägg till AutoPkg-repo
        run: |
          autopkg repo-add https://github.com/autopkg/recipes.git || echo "Repo redan tillagt"

      - name: Ange Munki-repo path
        run: |
          defaults write com.googlecode.munki.munkiimport repo_path "$GITHUB_WORKSPACE"

      - name: Kör AutoPkg-recept
        run: |
          autopkg run -v googlechrome.munki AdobeReader.munki || echo "Misslyckades att köra något recept"

      - name: Commit ändringar
        run: |
          git config user.name "MunkiBot"
          git config user.email "bot@munki.local"
          git checkout -b autopkg-update-$(date +'%Y%m%d') || git checkout autopkg-update-$(date +'%Y%m%d')
          git add .
          git commit -m "AutoPkg: uppdaterade pkgs och pkgsinfo" || echo "Inga ändringar att committa"
          git push origin HEAD

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AutoPkg uppdateringar"
          body: "Automatiska uppdateringar från AutoPkg"
          base: main
          branch: autopkg-update-$(date +'%Y%m%d')
